language: android
jdk: oraclejdk8
sudo: required

env:
  global:
    -ANDROID_API_LEVEL=29
    -ANDROID_EMULATOR_LEVEL=19
    -ANDROID_BUILD_TOOLS_VERSION=29.0.3
    -ADB_INSTALL_TIMEOUT=20
    -ANDROID_TAG=google_apis
    -QEMU_AUDIO_DRV=none

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLD_VERSION
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMULATOR_LEVEL
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19 
    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_EMULATOR_LEVEL

licences:
  - android-sdk-preview-licence- .+
  - android-sdk-licence- .+
  - google-gdk-licence- .+

cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" >  "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - chmod +x gradlew
  - ./gradlew dependencies || true

before_script:
  - android list targets
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-window &
  - android-wait_for_emulator

script:
  - ./gradlew dependencyCheckAnalyze build
  - adb shell input keyevent 82
  - ./gradlew connectedCheck -PdisablePreDex --stacktrace
